theme = "default"

[style]
mode = "plain"
separator = " | "

[[segments]]
id = "model"
enabled = true

[segments.icon]
plain = "🤖"
nerd_font = ""

[segments.colors.icon]
c16 = 14

[segments.colors.text]
c16 = 14

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "directory"
enabled = true

[segments.icon]
plain = "📁"
nerd_font = "󰉋"

[segments.colors.icon]
c16 = 11

[segments.colors.text]
c16 = 10

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "git"
enabled = true

[segments.icon]
plain = "🌿"
nerd_font = "󰊢"

[segments.colors.icon]
c16 = 12

[segments.colors.text]
c16 = 12

[segments.styles]
text_bold = false

[segments.options]
show_sha = false

[[segments]]
id = "context_window"
enabled = true

[segments.icon]
plain = "⚡️"
nerd_font = ""

[segments.colors.icon]
c16 = 13

[segments.colors.text]
c16 = 13

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "usage"
enabled = false

[segments.icon]
plain = "📊"
nerd_font = "󰪞"

[segments.colors.icon]
c16 = 14

[segments.colors.text]
c16 = 14

[segments.styles]
text_bold = false

[segments.options]
timeout = 2
cache_duration = 180
api_base_url = "https://api.anthropic.com"

[[segments]]
id = "cost"
enabled = false

[segments.icon]
plain = "💰"
nerd_font = ""

[segments.colors.icon]
c16 = 3

[segments.colors.text]
c16 = 3

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "session"
enabled = false

[segments.icon]
plain = "⏱️"
nerd_font = "󱦻"

[segments.colors.icon]
c16 = 2

[segments.colors.text]
c16 = 2

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "output_style"
enabled = false

[segments.icon]
plain = "🎯"
nerd_font = "󱋵"

[segments.colors.icon]
c16 = 6

[segments.colors.text]
c16 = 6

[segments.styles]
text_bold = false

[segments.options]
