theme = "gruvbox"

[style]
mode = "nerd_font"
separator = " | "

[[segments]]
id = "model"
enabled = true

[segments.icon]
plain = "🤖"
nerd_font = ""

[segments.colors.icon]
c256 = 208

[segments.colors.text]
c256 = 208

[segments.styles]
text_bold = true

[segments.options]

[[segments]]
id = "directory"
enabled = true

[segments.icon]
plain = "📁"
nerd_font = "󰉋"

[segments.colors.icon]
c256 = 142

[segments.colors.text]
c256 = 142

[segments.styles]
text_bold = true

[segments.options]

[[segments]]
id = "git"
enabled = true

[segments.icon]
plain = "🌿"
nerd_font = "󰊢"

[segments.colors.icon]
c256 = 109

[segments.colors.text]
c256 = 109

[segments.styles]
text_bold = true

[segments.options]
show_sha = false

[[segments]]
id = "context_window"
enabled = true

[segments.icon]
plain = "⚡️"
nerd_font = ""

[segments.colors.icon]
c16 = 5

[segments.colors.text]
c16 = 5

[segments.styles]
text_bold = true

[segments.options]

[[segments]]
id = "usage"
enabled = false

[segments.icon]
plain = "📊"
nerd_font = "󰪞"

[segments.colors.icon]
c16 = 14

[segments.colors.text]
c16 = 14

[segments.styles]
text_bold = false

[segments.options]
api_base_url = "https://api.anthropic.com"
cache_duration = 180
timeout = 2

[[segments]]
id = "cost"
enabled = false

[segments.icon]
plain = "💰"
nerd_font = ""

[segments.colors.icon]
c256 = 214

[segments.colors.text]
c256 = 214

[segments.styles]
text_bold = true

[segments.options]

[[segments]]
id = "session"
enabled = false

[segments.icon]
plain = "⏱️"
nerd_font = "󱦻"

[segments.colors.icon]
c256 = 142

[segments.colors.text]
c256 = 142

[segments.styles]
text_bold = true

[segments.options]

[[segments]]
id = "output_style"
enabled = false

[segments.icon]
plain = "🎯"
nerd_font = "󱋵"

[segments.colors.icon]
c256 = 109

[segments.colors.text]
c256 = 109

[segments.styles]
text_bold = true

[segments.options]
