theme = "powerline-dark"

[style]
mode = "nerd_font"
separator = ""

[[segments]]
id = "model"
enabled = true

[segments.icon]
plain = "🤖"
nerd_font = ""

[segments.colors.icon]
r = 255
g = 255
b = 255

[segments.colors.text]
r = 255
g = 255
b = 255

[segments.colors.background]
r = 45
g = 45
b = 45

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "directory"
enabled = true

[segments.icon]
plain = "📁"
nerd_font = "󰉋"

[segments.colors.icon]
r = 255
g = 255
b = 255

[segments.colors.text]
r = 255
g = 255
b = 255

[segments.colors.background]
r = 139
g = 69
b = 19

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "git"
enabled = true

[segments.icon]
plain = "🌿"
nerd_font = "󰊢"

[segments.colors.icon]
r = 255
g = 255
b = 255

[segments.colors.text]
r = 255
g = 255
b = 255

[segments.colors.background]
r = 64
g = 64
b = 64

[segments.styles]
text_bold = false

[segments.options]
show_sha = false

[[segments]]
id = "context_window"
enabled = true

[segments.icon]
plain = "⚡️"
nerd_font = ""

[segments.colors.icon]
r = 209
g = 213
b = 219

[segments.colors.text]
r = 209
g = 213
b = 219

[segments.colors.background]
r = 55
g = 65
b = 81

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "usage"
enabled = false

[segments.icon]
plain = "📊"
nerd_font = "󰪞"

[segments.colors.icon]
c16 = 14

[segments.colors.text]
c16 = 14

[segments.styles]
text_bold = false

[segments.options]
api_base_url = "https://api.anthropic.com"
timeout = 2
cache_duration = 180

[[segments]]
id = "cost"
enabled = false

[segments.icon]
plain = "💰"
nerd_font = ""

[segments.colors.icon]
r = 229
g = 192
b = 123

[segments.colors.text]
r = 229
g = 192
b = 123

[segments.colors.background]
r = 40
g = 44
b = 52

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "session"
enabled = false

[segments.icon]
plain = "⏱️"
nerd_font = "󱦻"

[segments.colors.icon]
r = 163
g = 190
b = 140

[segments.colors.text]
r = 163
g = 190
b = 140

[segments.colors.background]
r = 45
g = 50
b = 59

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "output_style"
enabled = false

[segments.icon]
plain = "🎯"
nerd_font = "󱋵"

[segments.colors.icon]
r = 129
g = 161
b = 193

[segments.colors.text]
r = 129
g = 161
b = 193

[segments.colors.background]
r = 50
g = 56
b = 66

[segments.styles]
text_bold = false

[segments.options]
