theme = "powerline-rose-pine"

[style]
mode = "nerd_font"
separator = ""

[[segments]]
id = "model"
enabled = true

[segments.icon]
plain = "🤖"
nerd_font = ""

[segments.colors.icon]
r = 235
g = 188
b = 186

[segments.colors.text]
r = 235
g = 188
b = 186

[segments.colors.background]
r = 25
g = 23
b = 36

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "directory"
enabled = true

[segments.icon]
plain = "📁"
nerd_font = "󰉋"

[segments.colors.icon]
r = 196
g = 167
b = 231

[segments.colors.text]
r = 196
g = 167
b = 231

[segments.colors.background]
r = 38
g = 35
b = 58

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "git"
enabled = true

[segments.icon]
plain = "🌿"
nerd_font = "󰊢"

[segments.colors.icon]
r = 156
g = 207
b = 216

[segments.colors.text]
r = 156
g = 207
b = 216

[segments.colors.background]
r = 31
g = 29
b = 46

[segments.styles]
text_bold = false

[segments.options]
show_sha = false

[[segments]]
id = "context_window"
enabled = true

[segments.icon]
plain = "⚡️"
nerd_font = ""

[segments.colors.icon]
r = 224
g = 222
b = 244

[segments.colors.text]
r = 224
g = 222
b = 244

[segments.colors.background]
r = 82
g = 79
b = 103

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "usage"
enabled = false

[segments.icon]
plain = "📊"
nerd_font = "󰪞"

[segments.colors.icon]
c16 = 14

[segments.colors.text]
c16 = 14

[segments.styles]
text_bold = false

[segments.options]
api_base_url = "https://api.anthropic.com"
cache_duration = 180
timeout = 2

[[segments]]
id = "cost"
enabled = false

[segments.icon]
plain = "💰"
nerd_font = ""

[segments.colors.icon]
r = 246
g = 193
b = 119

[segments.colors.text]
r = 246
g = 193
b = 119

[segments.colors.background]
r = 35
g = 33
b = 54

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "session"
enabled = false

[segments.icon]
plain = "⏱️"
nerd_font = "󱦻"

[segments.colors.icon]
r = 156
g = 207
b = 216

[segments.colors.text]
r = 156
g = 207
b = 216

[segments.colors.background]
r = 42
g = 39
b = 63

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "output_style"
enabled = false

[segments.icon]
plain = "🎯"
nerd_font = "󱋵"

[segments.colors.icon]
r = 49
g = 116
b = 143

[segments.colors.text]
r = 49
g = 116
b = 143

[segments.colors.background]
r = 38
g = 35
b = 58

[segments.styles]
text_bold = false

[segments.options]
