theme = "powerline-tokyo-night"

[style]
mode = "nerd_font"
separator = ""

[[segments]]
id = "model"
enabled = true

[segments.icon]
plain = "🤖"
nerd_font = ""

[segments.colors.icon]
r = 252
g = 167
b = 234

[segments.colors.text]
r = 252
g = 167
b = 234

[segments.colors.background]
r = 25
g = 27
b = 41

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "directory"
enabled = true

[segments.icon]
plain = "📁"
nerd_font = "󰉋"

[segments.colors.icon]
r = 130
g = 170
b = 255

[segments.colors.text]
r = 130
g = 170
b = 255

[segments.colors.background]
r = 47
g = 51
b = 77

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "git"
enabled = true

[segments.icon]
plain = "🌿"
nerd_font = "󰊢"

[segments.colors.icon]
r = 195
g = 232
b = 141

[segments.colors.text]
r = 195
g = 232
b = 141

[segments.colors.background]
r = 30
g = 32
b = 48

[segments.styles]
text_bold = false

[segments.options]
show_sha = false

[[segments]]
id = "context_window"
enabled = true

[segments.icon]
plain = "⚡️️"
nerd_font = ""

[segments.colors.icon]
r = 192
g = 202
b = 245

[segments.colors.text]
r = 192
g = 202
b = 245

[segments.colors.background]
r = 61
g = 89
b = 161

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "usage"
enabled = false

[segments.icon]
plain = "📊"
nerd_font = "󰪞"

[segments.colors.icon]
c16 = 14

[segments.colors.text]
c16 = 14

[segments.styles]
text_bold = false

[segments.options]
api_base_url = "https://api.anthropic.com"
cache_duration = 180
timeout = 2

[[segments]]
id = "cost"
enabled = false

[segments.icon]
plain = "💰"
nerd_font = ""

[segments.colors.icon]
r = 224
g = 175
b = 104

[segments.colors.text]
r = 224
g = 175
b = 104

[segments.colors.background]
r = 36
g = 40
b = 59

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "session"
enabled = false

[segments.icon]
plain = "⏱️"
nerd_font = "󱫓"

[segments.colors.icon]
r = 158
g = 206
b = 106

[segments.colors.text]
r = 158
g = 206
b = 106

[segments.colors.background]
r = 41
g = 46
b = 66

[segments.styles]
text_bold = false

[segments.options]

[[segments]]
id = "output_style"
enabled = false

[segments.icon]
plain = "🎯"
nerd_font = "󱋵"

[segments.colors.icon]
r = 125
g = 207
b = 255

[segments.colors.text]
r = 125
g = 207
b = 255

[segments.colors.background]
r = 32
g = 35
b = 52

[segments.styles]
text_bold = false

[segments.options]
